import { sourceMultimetri } from '../sourceMultimetri/source.entity';

export const source: sourceMultimetri[] = [
    {
        type: 1,
        name: 'PowerEqAux§_INT',
        description: 'Potenza attiva trifase - d3scription - Letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320539E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'PowerEqAux§_Onchange',
        description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: '+PowerEqAux§_Onchange',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 1,
        name: 'PowerEqAux§',
        description: 'Potenza attiva trifase - d3scription [kW] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'PowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 1,
        name: 'ReactPowerEqAux§_INT',
        description: 'Potenza reattiva trifase - d3scription [kvar] - letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320541E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'ReactPowerEqAux§',
        description: 'Potenza reattiva trifase - d3scription [kvar] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'ReactPowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 1,
        name: 'CosphiAux§_INT',
        description: 'Fattore di potenza - d3scription - Letto come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320549W',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'CosphiAux§',
        description: 'Fattore di potenza - d3scription - Convertito',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'CosphiAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 1,
        name: 'EnergyAux§',
        description: 'Energia attiva assorbita (positiva) - d3scription [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320593E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'NegEnergyAux§',
        description: 'Energia attiva ceduta (negativa) - d3scription [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320595E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'VoltageL1NAux§',
        description: 'Tensione tra fase 1 e neutro - d3scription [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320510E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'VoltageL2NAux§',
        description: 'Tensione tra fase 2 e neutro - d3scription [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320512E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'VoltageL3NAux§',
        description: 'Tensione tra fase 3 e neutro - d3scription [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320514E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'CurrentL1Aux§',
        description: 'Corrente fase 1 - d3scription [A]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320481E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'CurrentL2Aux§',
        description: 'Corrente fase 2 - d3scription [A]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320483E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'CurrentL3Aux§',
        description: 'Corrente fase 3 - d3scription [A]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320485E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 1,
        name: 'IdlePowerAux§',
        description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'IdlePowerAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 1,
        name: 'StatoONAux§',
        description: '1 = stato ON, 0 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoONAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 1,
        name: 'StatoSTANDBYAux§',
        description: '0 = stato ON, 1 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoSTANDBYAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 2,
        name: 'PowerEqAux§_UNS',
        description: 'Potenza attiva trifase - IME tipo 2 - d3scription - letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '44117E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 2,
        name: 'SIGNPowerEqAux§',
        description: 'Segno potenza attiva trifase - IME tipo 2 - d3scription - 0 negativo, 1 positivo',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '44123',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 2,
        name: 'PowerEqAux§',
        description: 'Potenza attiva trifase - IME tipo 2 - d3scription - [kW] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'PowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 2,
        name: 'PowerEqAux§_Onchange',
        description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'PowerEqAux§_Onchange',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 2,
        name: 'ReactPowerEqAux§_UNS',
        description: 'Potenza reattiva trifase - IME tipo 2 - d3scription - [kvar] - letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '44119E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 2,
        name: 'SIGNReactPowerEqAux§',
        description: 'Segno potenza reattiva trifase - IME tipo 2 - d3scription - - 0 negativo, 1 positivo',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '44124',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 2,
        name: 'ReactPowerEqAux§',
        description: 'Potenza reattiva trifase - IME tipo 2 - d3scription - [kvar] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'ReactPowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 2,
        name: 'CosphiAux§',
        description: 'Fattore di potenza - IME tipo 2 - d3scription -',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '44133I',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 2,
        name: 'EnergyAux§',
        description: 'Energia attiva assorbita (positiva) -  IME tipo 2 - d3scription - [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '44125E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 2,
        name: 'NegEnergyAux§',
        description: 'Energia attiva ceduta (negativa) -  IME tipo 2 - d3scription - [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '44129E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 2,
        name: 'VoltageL1NAux§',
        description: 'Tensione tra fase 1 e neutro - IME tipo 2 - d3scription - [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '44097E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 2,
        name: 'CurrentL1Aux§',
        description: 'Corrente fase 1 - IME tipo 2 - d3scription - [A]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '44103E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 2,
        name: 'IdlePowerAux§',
        description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'IdlePowerAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 2,
        name: 'StatoONAux§',
        description: '1 = stato ON, 0 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoONAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 2,
        name: 'StatoSTANDBYAux§',
        description: '0 = stato ON, 1 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoSTANDBYAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 3,
        name: 'PowerEqAux§_INT',
        description: 'Potenza attiva trifase - IME tipo 3 - d3scription - Letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320539E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 3,
        name: 'PowerEqAux§_Onchange',
        description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'PowerEqAux§_Onchange',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 3,
        name: 'PowerEqAux§',
        description: 'Potenza attiva trifase - IME tipo 3 - d3scription - [kW] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'PowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 3,
        name: 'ReactPowerEqAux§_INT',
        description: 'Potenza reattiva trifase - IME tipo 3 - d3scription - [kvar] - letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320524E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 3,
        name: 'ReactPowerEqAux§',
        description: 'Potenza reattiva trifase- IME tipo 3 - d3scription - [kvar] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'ReactPowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 3,
        name: 'CosphiAux§_INT',
        description: 'Fattore di potenza - IME tipo 3 - d3scription - Letto come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320528W',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 3,
        name: 'CosphiAux§',
        description: 'Fattore di potenza - IME tipo 3 - d3scription - Convertito',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'CosphiAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 3,
        name: 'EnergyAux§',
        description: 'Energia attiva assorbita (positiva) - IME tipo 3 - d3scription - [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320533E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 3,
        name: 'NegEnergyAux§',
        description: 'Energia attiva ceduta (negativa)- IME tipo 3 - d3scription - [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320535E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 3,
        name: 'VoltageL1NAux§',
        description: 'Tensione tra fase 1 e fase 2- IME tipo 3 - d3scription - [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320498E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 3,
        name: 'CurrentL1Aux§',
        description: 'Corrente fase 1 - IME tipo 3 - d3scription - [A]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320481E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 3,
        name: 'IdlePowerAux§',
        description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'IdlePowerAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 3,
        name: 'StatoONAux§',
        description: '1 = stato ON, 0 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoONAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 3,
        name: 'StatoSTANDBYAux§',
        description: '0 = stato ON, 1 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoSTANDBYAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 4,
        name: 'PowerEqAux§_INT',
        description: 'Potenza attiva trifase - IME tipo 4 - d3scription - Letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320523E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 4,
        name: 'PowerEqAux§_Onchange',
        description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'PowerEqAux§_Onchange',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 4,
        name: 'PowerEqAux§',
        description: 'Potenza attiva trifase - IME tipo 4 - d3scription - [kW] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'PowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 4,
        name: 'ReactPowerEqAux§_INT',
        description: 'Potenza reattiva trifase - IME tipo 4 - d3scription - [kvar] - letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320524E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 4,
        name: 'ReactPowerEqAux§',
        description: 'Potenza reattiva trifase - IME tipo 4 - d3scription - [kvar] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'ReactPowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 4,
        name: 'CosphiAux§_INT',
        description: 'Fattore di potenza - IME tipo 4 - d3scription - Letto come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320528W',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 4,
        name: 'CosphiAux§',
        description: 'Fattore di potenza - IME tipo 4 - d3scription - Convertito',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'CosphiAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 4,
        name: 'EnergyAux§',
        description: 'Energia attiva assorbita (positiva) - IME tipo 4 - d3scription - [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320533E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 4,
        name: 'NegEnergyAux§',
        description: 'Energia attiva ceduta (negativa) - IME tipo 4 - d3scription - [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320541E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 4,
        name: 'VoltageL1NAux§',
        description: 'Tensione tra fase 1 e neutro - IME tipo 4 - d3scription - [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320495E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 4,
        name: 'VoltageL1L2Aux§',
        description: 'Tensione tra fase 1 e fase 2 - IME tipo 4 - d3scription - [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320498W',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 4,
        name: 'CurrentL1Aux§',
        description: 'Corrente fase 1 - IME tipo 4 - d3scription - [A]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '+320481E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 4,
        name: 'IdlePowerAux§',
        description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'IdlePowerAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 4,
        name: 'StatoONAux§',
        description: '1 = stato ON, 0 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoONAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 4,
        name: 'StatoSTANDBYAux§',
        description: '0 = stato ON, 1 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoSTANDBYAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 5,
        name: 'PowerEqAux§_INT',
        description: 'Potenza attiva trifase - d3scription - Letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '45934H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'PowerEqAux§_Onchange',
        description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'PowerEqAux§_Onchange',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 5,
        name: 'PowerEqAux§',
        description: 'Potenza attiva trifase - d3scription [kW] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'PowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 5,
        name: 'ReactPowerEqAux§_INT',
        description: 'Potenza reattiva trifase - d3scription [kvar] - letta come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '49010H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'ReactPowerEqAux§',
        description: 'Potenza reattiva trifase - d3scription [kvar] - Convertita',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'ReactPowerEqAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 5,
        name: 'CosphiAux§_INT',
        description: 'Fattore di potenza - d3scription - Letto come INTEGER',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '45958H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'CosphiAux§',
        description: 'Fattore di potenza - d3scription - Convertito',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'CosphiAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 5,
        name: 'EnergyAux§',
        description: 'Energia attiva assorbita (positiva) - d3scription [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '48000E',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'NegEnergyAux§',
        description: 'Energia attiva ceduta (negativa) - d3scription [kWh]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '46020H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'VoltageL1NAux§',
        description: 'Tensione tra fase 1 e neutro - d3scription [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '45952H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'VoltageL2NAux§',
        description: 'Tensione tra fase 2 e neutro - d3scription [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '45954H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'VoltageL3NAux§',
        description: 'Tensione tra fase 3 e neutro - d3scription [V]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '45956H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'CurrentL1Aux§',
        description: 'Corrente fase 1 - d3scription [A]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '45944H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'CurrentL2Aux§',
        description: 'Corrente fase 2 - d3scription [A]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '45946H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'CurrentL3Aux§',
        description: 'Corrente fase 3 - d3scription [A]',
        serverName: 'MODBUS',
        topicName: 'C',
        addressModBus: '45948H',
        addressDeviceId: '@',
        addressIp: 'ç',
    },
    {
        type: 5,
        name: 'IdlePowerAux§',
        description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'IdlePowerAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 5,
        name: 'StatoONAux§',
        description: '1 = stato ON, 0 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoONAux§',
        addressDeviceId: '',
        addressIp: '',
    },
    {
        type: 5,
        name: 'StatoSTANDBYAux§',
        description: '0 = stato ON, 1 = stato STANDBY',
        serverName: 'MEM',
        topicName: 'RET',
        addressModBus: 'StatoSTANDBYAux§',
        addressDeviceId: '',
        addressIp: '',
    },
]