import { SourceMultimetri } from '../sourceMultimetri/sourceMultimetri.entity';

export const sourceMultimetri: SourceMultimetri[] = [
    {
        Type: '1',
        Name: 'PowerEqAux§_INT',
        Description: 'Potenza attiva trifase - d3scription - Letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320539E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'PowerEqAux§_Onchange',
        Description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§_Onchange',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '1',
        Name: 'PowerEqAux§',
        Description: 'Potenza attiva trifase - d3scription [kW] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '1',
        Name: 'ReactPowerEqAux§_INT',
        Description: 'Potenza reattiva trifase - d3scription [kvar] - letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320541E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'ReactPowerEqAux§',
        Description: 'Potenza reattiva trifase - d3scription [kvar] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'ReactPowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '1',
        Name: 'CosphiAux§_INT',
        Description: 'Fattore di potenza - d3scription - Letto come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320549W',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'CosphiAux§',
        Description: 'Fattore di potenza - d3scription - Convertito',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'CosphiAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '1',
        Name: 'EnergyAux§',
        Description: 'Energia attiva assorbita (positiva) - d3scription [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320593E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'NegEnergyAux§',
        Description: 'Energia attiva ceduta (negativa) - d3scription [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320595E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'VoltageL1NAux§',
        Description: 'Tensione tra fase 1 e neutro - d3scription [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320510E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'VoltageL2NAux§',
        Description: 'Tensione tra fase 2 e neutro - d3scription [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320512E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'VoltageL3NAux§',
        Description: 'Tensione tra fase 3 e neutro - d3scription [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320514E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'CurrentL1Aux§',
        Description: 'Corrente fase 1 - d3scription [A]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320481E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'CurrentL2Aux§',
        Description: 'Corrente fase 2 - d3scription [A]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320483E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'CurrentL3Aux§',
        Description: 'Corrente fase 3 - d3scription [A]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320485E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '1',
        Name: 'IdlePowerAux§',
        Description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'IdlePowerAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '1',
        Name: 'StatoONAux§',
        Description: '1 = stato ON, 0 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoONAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '1',
        Name: 'StatoSTANDBYAux§',
        Description: '0 = stato ON, 1 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoSTANDBYAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '2',
        Name: 'PowerEqAux§_UNS',
        Description: 'Potenza attiva trifase - IME tipo 2 - d3scription - letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '44117E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '2',
        Name: 'SIGNPowerEqAux§',
        Description: 'Segno potenza attiva trifase - IME tipo 2 - d3scription - 0 negativo, 1 positivo',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '44123',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '2',
        Name: 'PowerEqAux§',
        Description: 'Potenza attiva trifase - IME tipo 2 - d3scription - [kW] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '2',
        Name: 'PowerEqAux§_Onchange',
        Description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§_Onchange',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '2',
        Name: 'ReactPowerEqAux§_UNS',
        Description: 'Potenza reattiva trifase - IME tipo 2 - d3scription - [kvar] - letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '44119E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '2',
        Name: 'SIGNReactPowerEqAux§',
        Description: 'Segno potenza reattiva trifase - IME tipo 2 - d3scription - - 0 negativo, 1 positivo',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '44124',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '2',
        Name: 'ReactPowerEqAux§',
        Description: 'Potenza reattiva trifase - IME tipo 2 - d3scription - [kvar] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'ReactPowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '2',
        Name: 'CosphiAux§',
        Description: 'Fattore di potenza - IME tipo 2 - d3scription -',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '44133I',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '2',
        Name: 'EnergyAux§',
        Description: 'Energia attiva assorbita (positiva) -  IME tipo 2 - d3scription - [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '44125E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '2',
        Name: 'NegEnergyAux§',
        Description: 'Energia attiva ceduta (negativa) -  IME tipo 2 - d3scription - [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '44129E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '2',
        Name: 'VoltageL1NAux§',
        Description: 'Tensione tra fase 1 e neutro - IME tipo 2 - d3scription - [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '44097E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '2',
        Name: 'CurrentL1Aux§',
        Description: 'Corrente fase 1 - IME tipo 2 - d3scription - [A]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '44103E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '2',
        Name: 'IdlePowerAux§',
        Description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'IdlePowerAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '2',
        Name: 'StatoONAux§',
        Description: '1 = stato ON, 0 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoONAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '2',
        Name: 'StatoSTANDBYAux§',
        Description: '0 = stato ON, 1 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoSTANDBYAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '3',
        Name: 'PowerEqAux§_INT',
        Description: 'Potenza attiva trifase - IME tipo 3 - d3scription - Letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320539E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '3',
        Name: 'PowerEqAux§_Onchange',
        Description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§_Onchange',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '3',
        Name: 'PowerEqAux§',
        Description: 'Potenza attiva trifase - IME tipo 3 - d3scription - [kW] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '3',
        Name: 'ReactPowerEqAux§_INT',
        Description: 'Potenza reattiva trifase - IME tipo 3 - d3scription - [kvar] - letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320524E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '3',
        Name: 'ReactPowerEqAux§',
        Description: 'Potenza reattiva trifase- IME tipo 3 - d3scription - [kvar] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'ReactPowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '3',
        Name: 'CosphiAux§_INT',
        Description: 'Fattore di potenza - IME tipo 3 - d3scription - Letto come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320528W',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '3',
        Name: 'CosphiAux§',
        Description: 'Fattore di potenza - IME tipo 3 - d3scription - Convertito',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'CosphiAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '3',
        Name: 'EnergyAux§',
        Description: 'Energia attiva assorbita (positiva) - IME tipo 3 - d3scription - [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320533E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '3',
        Name: 'NegEnergyAux§',
        Description: 'Energia attiva ceduta (negativa)- IME tipo 3 - d3scription - [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320535E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '3',
        Name: 'VoltageL1NAux§',
        Description: 'Tensione tra fase 1 e fase 2- IME tipo 3 - d3scription - [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320498E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '3',
        Name: 'CurrentL1Aux§',
        Description: 'Corrente fase 1 - IME tipo 3 - d3scription - [A]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320481E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '3',
        Name: 'IdlePowerAux§',
        Description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'IdlePowerAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '3',
        Name: 'StatoONAux§',
        Description: '1 = stato ON, 0 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoONAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '3',
        Name: 'StatoSTANDBYAux§',
        Description: '0 = stato ON, 1 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoSTANDBYAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '4',
        Name: 'PowerEqAux§_INT',
        Description: 'Potenza attiva trifase - IME tipo 4 - d3scription - Letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320523E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '4',
        Name: 'PowerEqAux§_Onchange',
        Description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§_Onchange',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '4',
        Name: 'PowerEqAux§',
        Description: 'Potenza attiva trifase - IME tipo 4 - d3scription - [kW] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '4',
        Name: 'ReactPowerEqAux§_INT',
        Description: 'Potenza reattiva trifase - IME tipo 4 - d3scription - [kvar] - letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320524E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '4',
        Name: 'ReactPowerEqAux§',
        Description: 'Potenza reattiva trifase - IME tipo 4 - d3scription - [kvar] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'ReactPowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '4',
        Name: 'CosphiAux§_INT',
        Description: 'Fattore di potenza - IME tipo 4 - d3scription - Letto come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320528W',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '4',
        Name: 'CosphiAux§',
        Description: 'Fattore di potenza - IME tipo 4 - d3scription - Convertito',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'CosphiAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '4',
        Name: 'EnergyAux§',
        Description: 'Energia attiva assorbita (positiva) - IME tipo 4 - d3scription - [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320533E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '4',
        Name: 'NegEnergyAux§',
        Description: 'Energia attiva ceduta (negativa) - IME tipo 4 - d3scription - [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320541E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '4',
        Name: 'VoltageL1NAux§',
        Description: 'Tensione tra fase 1 e neutro - IME tipo 4 - d3scription - [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320495E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '4',
        Name: 'VoltageL1L2Aux§',
        Description: 'Tensione tra fase 1 e fase 2 - IME tipo 4 - d3scription - [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320498W',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '4',
        Name: 'CurrentL1Aux§',
        Description: 'Corrente fase 1 - IME tipo 4 - d3scription - [A]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '+320481E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '4',
        Name: 'IdlePowerAux§',
        Description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'IdlePowerAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '4',
        Name: 'StatoONAux§',
        Description: '1 = stato ON, 0 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoONAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '4',
        Name: 'StatoSTANDBYAux§',
        Description: '0 = stato ON, 1 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoSTANDBYAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '5',
        Name: 'PowerEqAux§_INT',
        Description: 'Potenza attiva trifase - d3scription - Letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '45934H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'PowerEqAux§_Onchange',
        Description: 'Per ONCHANGE (script): stesso valore di PowerEqAux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§_Onchange',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '5',
        Name: 'PowerEqAux§',
        Description: 'Potenza attiva trifase - d3scription [kW] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'PowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '5',
        Name: 'ReactPowerEqAux§_INT',
        Description: 'Potenza reattiva trifase - d3scription [kvar] - letta come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '49010H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'ReactPowerEqAux§',
        Description: 'Potenza reattiva trifase - d3scription [kvar] - Convertita',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'ReactPowerEqAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '5',
        Name: 'CosphiAux§_INT',
        Description: 'Fattore di potenza - d3scription - Letto come INTEGER',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '45958H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'CosphiAux§',
        Description: 'Fattore di potenza - d3scription - Convertito',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'CosphiAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '5',
        Name: 'EnergyAux§',
        Description: 'Energia attiva assorbita (positiva) - d3scription [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '48000E',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'NegEnergyAux§',
        Description: 'Energia attiva ceduta (negativa) - d3scription [kWh]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '46020H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'VoltageL1NAux§',
        Description: 'Tensione tra fase 1 e neutro - d3scription [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '45952H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'VoltageL2NAux§',
        Description: 'Tensione tra fase 2 e neutro - d3scription [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '45954H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'VoltageL3NAux§',
        Description: 'Tensione tra fase 3 e neutro - d3scription [V]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '45956H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'CurrentL1Aux§',
        Description: 'Corrente fase 1 - d3scription [A]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '45944H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'CurrentL2Aux§',
        Description: 'Corrente fase 2 - d3scription [A]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '45946H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'CurrentL3Aux§',
        Description: 'Corrente fase 3 - d3scription [A]',
        ServerName: 'MODBUS',
        TopicName: 'C',
        AddressModBus: '45948H',
        AddressDeviceId: '@',
        AddressIp: 'ç',
    },
    {
        Type: '5',
        Name: 'IdlePowerAux§',
        Description: 'Valore potenza passaggio ON -> STANDBY consumi elettrici Aux§',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'IdlePowerAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '5',
        Name: 'StatoONAux§',
        Description: '1 = stato ON, 0 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoONAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
    {
        Type: '5',
        Name: 'StatoSTANDBYAux§',
        Description: '0 = stato ON, 1 = stato STANDBY',
        ServerName: 'MEM',
        TopicName: 'RET',
        AddressModBus: 'StatoSTANDBYAux§',
        AddressDeviceId: '',
        AddressIp: '',
    },
]