import { SourceFotovoltaici } from '../sourceFotovoltaici/sourceFotovoltaici.entity';

export const sourceFotovoltaici: SourceFotovoltaici[] = 
[
    {
        DeviceType: "1",
        Name: "TEST",
        Description: "Potenza attiva trifase - d3scription - Letta come INTEGER",
        ServerName: "MODBUS",
        TopicName: "C",
        AddressModBus: "+320539E",
        AddressDeviceId: "@",
        AddressIp: "ç",
        Coef: "1",
        Offset: "0",
        LogEnabled: "0",
        AlEnabled: "0",
        AlBool: "0",
        MemTag: "0",
        MbsTcpEnabled: "0",
        MbsTcpFloat: "0",
        SnmpEnabled: "0",
        RTLogEnabled: "0",
        AlAutoAck: "0",
        ForceRO: "1",
        SnmpOID: "1",
        AutoType: "0",
        AlHint: "",
        AlHigh: "0",
        AlLow: "0",
        AlTimeDB: "0",
        AlLevelDB: "0",
        IVGroupA: "0",
        IVGroupB: "0",
        IVGroupC: "0",
        IVGroupD: "0",
        PageId: "1",
        RTLogWindow: "600",
        RTLogTimer: "10",
        LogDB: "-1",
        LogTimer: "60",
        AlLoLo: "", 
        AlHiHi: "",
        MbsTcpRegister: "1",
        MbsTcpCoef: "1",
        MbsTcpOffset: "0",
        EEN: "",
        ETO: "",
        ECC: "",
        ESU: "",
        EAT: "",
        ESH: "",
        SEN: "",
        STO: "",
        SSU: "",
        TEN: "",
        TSU: "",
        FEN: "",
        FFN: "",
        FCO: "",
        KPI: "0",
        UseCustomUnit: "0",
        Type: "1",
        Unit: "",
        AlStat: "0",
        ChangeTime: "44853,51111",
        TagValue: "0",
        TagQuality: "65472",
        AlType: "0"
    }
]