import { NextFunction, Request, Response } from "express";
import { Parser } from "json2csv";
import { varListGenerator } from "./varList.service";

export const downloadVarList = async (
    req: Request,
    res: Response,
    next: NextFunction
) => {
    try {
        const request = req.body;

        if (!Array.isArray(request) || request.length === 0) {
            res.status(400).json({ message: "Dati errati o mancanti" });
            return;
        }

        let combinedVarlist: any[] = [];

        for (const item of request) {
            const { model, auxQuantity, description, device, ipAddress } = item;

            if (!model || !auxQuantity || !device || !ipAddress) {
                res.status(400).json({ message: "Parametri obbligatori mancanti" });
                return;
            }

            const varlistPart = await varListGenerator({
                model,
                auxQuantity,
                description,
                device,
                ipAddress
            });

            combinedVarlist.push(...varlistPart);
        }

        const staticEntries = [
            {
                Name: "PlantType",
                Description: "",
                ServerName: "MEM",
                TopicName: "RET",
                Address: "PlantType",
                Coef: "1",
                Offset: "0",
                LogEnabled: "0",
                AlEnabled: "0",
                AlBool: "0",
                MemTag: "1",
                MbsTcpEnabled: "0",
                MbsTcpFloat: "0",
                SnmpEnabled: "0",
                RTLogEnabled: "0",
                AlAutoAck: "0",
                ForceRO: "0",
                SnmpOID: "1",
                AutoType: "0",
                AlHint: "",
                AlHigh: "0",
                AlLow: "0",
                AlTimeDB: "0",
                AlLevelDB: "0",
                IVGroupA: "0",
                IVGroupB: "0",
                IVGroupC: "0",
                IVGroupD: "0",
                PageId: "1",
                RTLogWindow: "600",
                RTLogTimer: "10",
                LogDB: "-1",
                LogTimer: "0",
                AlLoLo: "",
                AlHiHi: "",
                MbsTcpRegister: "1",
                MbsTcpCoef: "1",
                MbsTcpOffset: "0",
                EEN: "",
                ETO: "",
                ECC: "",
                ESU: "",
                EAT: "",
                ESH: "",
                SEN: "",
                STO: "",
                SSU: "",
                TEN: "",
                TSU: "",
                FEN: "",
                FFN: "",
                FCO: "",
                KPI: "0",
                UseCustomUnit: "0",
                Type: "6",
                Unit: "",
                AlStat: "0",
                ChangeTime: "10/10/2022 11:10",
                TagValue: "Auxiliaries",
                TagQuality: "65472",
                AlType: "0",
            },
            {
                Name: "REBIRTH",
                Description: "",
                ServerName: "MEM",
                TopicName: "RET",
                Address: "REBIRTH",
                Coef: "1",
                Offset: "0",
                LogEnabled: "0",
                AlEnabled: "0",
                AlBool: "0",
                MemTag: "1",
                MbsTcpEnabled: "0",
                MbsTcpFloat: "0",
                SnmpEnabled: "0",
                RTLogEnabled: "0",
                AlAutoAck: "0",
                ForceRO: "0",
                SnmpOID: "1",
                AutoType: "0",
                AlHint: "",
                AlHigh: "0",
                AlLow: "0",
                AlTimeDB: "0",
                AlLevelDB: "0",
                IVGroupA: "0",
                IVGroupB: "0",
                IVGroupC: "1",
                IVGroupD: "0",
                PageId: "1",
                RTLogWindow: "600",
                RTLogTimer: "10",
                LogDB: "-1",
                LogTimer: "0",
                AlLoLo: "",
                AlHiHi: "",
                MbsTcpRegister: "1",
                MbsTcpCoef: "1",
                MbsTcpOffset: "0",
                EEN: "",
                ETO: "",
                ECC: "",
                ESU: "",
                EAT: "",
                ESH: "",
                SEN: "",
                STO: "",
                SSU: "",
                TEN: "",
                TSU: "",
                FEN: "",
                FFN: "",
                FCO: "",
                KPI: "0",
                UseCustomUnit: "0",
                Type: "2",
                Unit: "",
                AlStat: "0",
                ChangeTime: "10/10/2022 11:10",
                TagValue: "0",
                TagQuality: "65472",
                AlType: "0"
            },
            {
                Name: "dataUltimaManutAltroInterventoMot1",
                Description: "data ultima manutenzione altro intervento",
                ServerName: "MEM",
                TopicName: "RET",
                Address: "dataUltimaManutAltroInterventoMot1",
                Coef: "1",
                Offset: "0",
                LogEnabled: "0",
                AlEnabled: "0",
                AlBool: "0",
                MemTag: "1",
                MbsTcpEnabled: "0",
                MbsTcpFloat: "0",
                SnmpEnabled: "0",
                RTLogEnabled: "0",
                AlAutoAck: "0",
                ForceRO: "0",
                SnmpOID: "1",
                AutoType: "0",
                AlHint: "",
                AlHigh: "0",
                AlLow: "0",
                AlTimeDB: "0",
                AlLevelDB: "0",
                IVGroupA: "1",
                IVGroupB: "0",
                IVGroupC: "0",
                IVGroupD: "0",
                PageId: "1",
                RTLogWindow: "600",
                RTLogTimer: "10",
                LogDB: "-1",
                LogTimer: "0",
                AlLoLo: "",
                AlHiHi: "",
                MbsTcpRegister: "1",
                MbsTcpCoef: "1",
                MbsTcpOffset: "0",
                EEN: "",
                ETO: "",
                ECC: "",
                ESU: "",
                EAT: "",
                ESH: "",
                SEN: "",
                STO: "",
                SSU: "",
                TEN: "",
                TSU: "",
                FEN: "",
                FFN: "",
                FCO: "",
                KPI: "0",
                UseCustomUnit: "0",
                Type: "3",
                Unit: "",
                AlStat: "0",
                ChangeTime: "11/10/2022 14:48",
                TagValue: "0",
                TagQuality: "65472",
                AlType: "0"
            },
            {
                Name: "resetOreAltroInterventoMot1",
                Description: "reset ore altro intervento",
                ServerName: "MEM",
                TopicName: "RET",
                Address: "resetOreAltroInterventoMot1",
                Coef: "1",
                Offset: "0",
                LogEnabled: "0",
                AlEnabled: "0",
                AlBool: "0",
                MemTag: "1",
                MbsTcpEnabled: "0",
                MbsTcpFloat: "0",
                SnmpEnabled: "0",
                RTLogEnabled: "0",
                AlAutoAck: "0",
                ForceRO: "0",
                SnmpOID: "1",
                AutoType: "0",
                AlHint: "",
                AlHigh: "0",
                AlLow: "0",
                AlTimeDB: "0",
                AlLevelDB: "0",
                IVGroupA: "0",
                IVGroupB: "0",
                IVGroupC: "1",
                IVGroupD: "0",
                PageId: "1",
                RTLogWindow: "600",
                RTLogTimer: "10",
                LogDB: "-1",
                LogTimer: "0",
                AlLoLo: "",
                AlHiHi: "",
                MbsTcpRegister: "1",
                MbsTcpCoef: "1",
                MbsTcpOffset: "0",
                EEN: "",
                ETO: "",
                ECC: "",
                ESU: "",
                EAT: "",
                ESH: "",
                SEN: "",
                STO: "",
                SSU: "",
                TEN: "",
                TSU: "",
                FEN: "",
                FFN: "",
                FCO: "",
                KPI: "0",
                UseCustomUnit: "0",
                Type: "3",
                Unit: "",
                AlStat: "0",
                ChangeTime: "11/10/2022 14:48",
                TagValue: "0",
                TagQuality: "65472",
                AlType: "0"
            }
        ]

        const fields = [
            'Id',
            'Name',
            'Description',
            'ServerName',
            'TopicName',
            'Address',
            'Coef',
            'Offset',
            'LogEnabled',
            'AlEnabled',
            'AlBool',
            'MemTag',
            'MbsTcpEnabled',
            'MbsTcpFloat',
            'SnmpEnabled',
            'RTLogEnabled',
            'AlAutoAck',
            'ForceRO',
            'SnmpOID',
            'AutoType',
            'AlHint',
            'AlHigh',
            'AlLow',
            'AlTimeDB',
            'AlLevelDB',
            'IVGroupA',
            'IVGroupB',
            'IVGroupC',
            'IVGroupD',
            'PageId',
            'RTLogWindow',
            'RTLogTimer',
            'LogDB',
            'LogTimer',
            'AlLoLo',
            'AlHiHi',
            'MbsTcpRegister',
            'MbsTcpCoef',
            'MbsTcpOffset',
            'EEN',
            'ETO',
            'ECC',
            'ESU',
            'EAT',
            'ESH',
            'SEN',
            'STO',
            'SSU',
            'TEN',
            'TSU',
            'FEN',
            'FFN',
            'FCO',
            'KPI',
            'UseCustomUnit',
            'Type',
            'Unit',
            'AlStat',
            'ChangeTime',
            'TagValue',
            'TagQuality',
            'AlType'
        ]

        combinedVarlist = [...staticEntries, ...combinedVarlist];

        const parser = new Parser({ fields, quote: '', delimiter: ';' });
        let csv = parser.parse(combinedVarlist);

        csv = csv.replace(/"/g, '');

        res.setHeader("Content-Type", "text/csv");
        res.setHeader("Content-Disposition", "attachment; filename=var_lst.csv");
        res.status(200).send(csv);
    } catch (err) {
        next(err);
    }
}